name: Build DIT-Transfer-Tools

on:
  push:
    branches: [ main, 'feature-*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.6.2'

    - name: Configure CMake
      run: |
        rm -rf build
        mkdir build
        cd build
        if [ "${{ runner.os }}" = "Windows" ]; then
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release
        else
          cmake .. -DCMAKE_BUILD_TYPE=Release
        fi

    - name: Build
      run: |
        cd build
        if [ "${{ runner.os }}" = "Windows" ]; then
          cmake --build . --config Release
        else
          cmake --build . --parallel
        fi

    - name: Test
      run: cd build && ctest -V

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DIT-${{ matrix.os }}
        path: build/DIT-Transfer-Tools*
        retention-days: 1
